version: "3"

services:
  app:
    build: .
    container_name: linebot-restaurant-go
    tty: true
    volumes:
      - .:/go/src/linebot-restaurant-go
    ports: 
      - 8080:8080
    environment: 
      - PORT=8080
    env_file: 
      - ./go-app/line.env
    command: "go run go-app/main.go"