settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: go-app
  path: .
  commands:
    install:
      status: true
      method: go build -o server
    run:
      status: true
      method: ./server
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
