version: "3"

services:
  app:
    build: .
    container_name: linebot-restaurant-go
    tty: true
    volumes:
      - .:/go/src/linebot-restaurant-go/go-app
    ports: 
      - 8080:8080
    environment: 
      - PORT=8080
    env_file: 
      - ./line.env
      - ./gcp.env
    command: "go run main.go"