version: "3.7"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: linebot-restaurant-go
    tty: true
    volumes:
      - .:/go/src/github.com/Fukkatsuso/linebot-restaurant-go/go-app
    ports: 
      - 8080:8080
    environment: 
      - PORT=8080
    env_file: 
      - ./line.env
      - ./gcp.env