name: Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - "datastore/**"
      - "README.md"
      - ".gitignore"

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/restaurant-search/image:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go-app

    steps:
      - uses: actions/checkout@v4

      - name: Google auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build a docker image
        run: docker build -f Dockerfile --target release -t $IMAGE .

      - name: Push the docker image
        run: docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy restaurant-search \
            --image $IMAGE \
            --project $GCP_PROJECT \
            --region $GCP_REGION \
            --platform managed \
            --set-env-vars "LINE_CHANNEL_ID=${{ secrets.LINE_CHANNEL_ID }}" \
            --set-env-vars "LINE_CHANNEL_SECRET=${{ secrets.LINE_CHANNEL_SECRET }}" \
            --set-env-vars "LINE_CHANNEL_TOKEN=${{ secrets.LINE_CHANNEL_TOKEN }}" \
            --set-env-vars "GCP_PLACES_API_KEY=${{ secrets.GCP_PLACES_API_KEY }}" \
            --set-env-vars "DATASTORE_PROJECT_ID=$GCP_PROJECT" \
            --allow-unauthenticated \
            --quiet
