name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Set secrets
        run: |
          echo 'env_variables:' >> go-app/secret.yaml
          echo '  LINE_CHANNEL_ID: "${{ secrets.LINE_CHANNEL_ID }}"' >> go-app/secret.yaml
          echo '  LINE_CHANNEL_SECRET: "${{ secrets.LINE_CHANNEL_SECRET }}"' >> go-app/secret.yaml
          echo '  LINE_CHANNEL_TOKEN: "${{ secrets.LINE_CHANNEL_TOKEN }}"' >> go-app/secret.yaml
          echo '  GCP_PLACES_API_KEY: "${{ secrets.GCP_PLACES_API_KEY }}"' >> go-app/secret.yaml
      
      - name: GCP Authenticate
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to GAE
        uses: GoogleCloudPlatform/github-actions/appengine-deploy@master
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          version: 1.0
          deliverables: go-app/app.yaml